# Generated by Django 2.1.2 on 2018-10-12 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChannelAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255, unique=True)),
                ('real_name', models.CharField(max_length=50, unique=True)),
                ('state', models.CharField(choices=[('START', '启用'), ('STOP', '停用')], default='START', max_length=10)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pop.Channel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChannelOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('user_id', models.IntegerField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pop.Channel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
