# Generated by Django 2.1.2 on 2018-10-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AddField(
            model_name='channelaccount',
            name='level',
            field=models.CharField(choices=[('NORMAL', '普通账户'), ('ADMIN', '管理员账户')], default='NORMAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='channelaccount',
            name='state',
            field=models.CharField(choices=[('START', '已启用'), ('STOP', '已停用')], default='START', max_length=10),
        ),
    ]
