# Generated by Django 2.1.2 on 2018-10-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0002_auto_20181013_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelaccount',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='channelaccount',
            name='real_name',
            field=models.CharField(max_length=50),
        ),
    ]
