# Generated by Django 2.1.2 on 2018-10-13 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0003_auto_20181013_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelaccount',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pop.Channel'),
        ),
    ]
