# Generated by Django 2.1.2 on 2018-10-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0004_auto_20181013_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('tel', models.CharField(max_length=50)),
                ('verification_code', models.CharField(max_length=10)),
                ('send_time', models.DateTimeField()),
                ('valid_time', models.DateTimeField()),
                ('verification_time', models.DateTimeField()),
                ('state', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
