# Generated by Django 2.1.2 on 2018-10-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0005_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='verification_time',
            field=models.DateTimeField(null=True),
        ),
    ]
